=== Oksihris/my_1web-xml/blogpage.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="blogpage">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="header"/>
        <xs:element name="header-desc"/>
        <xs:element name="article" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="content">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="theme"/>
                    <xs:element type="xs:string" name="description"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="inf-meta">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="inf"/>
                    <xs:element type="xs:string" name="author"/>
                    <xs:element name="keyWords">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="keyword" maxOccurs="unbounded" minOccurs="1"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="apps">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="appfile"/>
                          <xs:element name="applink" maxOccurs="unbounded" minOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="applink-name"/>
                                <xs:element type="xs:string" name="value"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="comms">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="comment" maxOccurs="unbounded" minOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="commentText"/>
                          <xs:element type="xs:string" name="comment-author"/>
                          <xs:element name="comment-tags">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="comment-tag" maxOccurs="unbounded" minOccurs="1"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Oksihris/my_1web-xml/blogpage.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<!DOCTYPE blogpage SYSTEM "blogpage.dtd">

<blogpage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="blogpage.xsd blogpage.xsd">

    <header>Artificial intelligence</header>
    <header-desc>Тут будуть розташовані останні новини штучного інтелекту!</header-desc>

    <article>
        <content>
            <theme>У США представили безпілотний трактор зі штучним інтелектом</theme>
            <description>
             "Каліфорнійський стартап Monarch Tractor презентував свій перший "розумний" трактор MK-V, який може виконувати сільськогосподарські завдання без водія. Кожен MK-V використовує шість системних модулів Jetson Xavier NX, які дають змогу переміщатися по полях, використовуючи лише камери."
            </description>
        </content>
        <inf-meta>
            <inf>2 грудня 2022</inf>
            <author>Oksana Khrystenko</author>
            <keyWords>
                <keyword>
                    AI
                </keyword>
                <keyword>
                    Tractor
                </keyword>
                <keyword>
                    MK-V
                </keyword>
            </keyWords>
            <apps>
                <appfile>Tractor.jpg</appfile>
                <applink>
                    <applink-name>Info</applink-name>
                    <value>https://www.ukrinform.ua/rubric-technology/3626524-u-ssa-predstavili-bezpilotnij-traktor-zi-stucnim-intelektom.html</value>
                </applink>
            </apps>
        </inf-meta>
        <comms>
            <comment>
                <commentText>Цікава інформація!</commentText>
                <comment-author>Марія</comment-author>
                <comment-tags>
                    <comment-tag>
                     Коментар
                    </comment-tag>
                </comment-tags>
            </comment>
            <comment>
                <commentText>Вау! Цікаво чи з'являться вони в Україні?</commentText>
                <comment-author>Тарас</comment-author>
                <comment-tags>
                    <comment-tag>
                      Коментар
                    </comment-tag>
                </comment-tags>
            </comment>
            <comment>
                <commentText>Дуже на це сподіваюсь!</commentText>
                <comment-author>Oksana Khrystenko</comment-author>
                <comment-tags>
                    <comment-tag>
                      Автор
                    </comment-tag>
                </comment-tags>
            </comment>
        </comms>

    </article>


    <article>
        <content>
            <theme>Штучний інтелект навчили передбачати ризик серцевого нападу й інсульту за рентгеном</theme>
            <description>
          Група американських дослідників розробила модель глибокого навчання на основі штучного інтелекту (ШІ), яка може передбачити ризик смерті від серцевого нападу або інсульту протягом 10-річного періоду лише за одним рентгенівським знімком грудної клітки.
          Дослідники навчили модель шукати на рентгенівських зображеннях закономірності, пов’язані з атеросклерозом, основною причиною серцево-судинних захворювань.

Ризик розраховується з використанням оцінки на основі таких змінних, як вік, стать, раса, артеріальний тиск, лікування гіпертонії, куріння, діабет 2 типу та аналізи крові.

Статини рекомендуються пацієнтам, у яких 10-річний ризик становить 7,5% або вище.
            </description>
        </content>
        <inf-meta>
            <inf>29 листопада 2022</inf>
            <author>Oksana Khrystenko</author>
            <keyWords>
                <keyword>
                    AI
                </keyword>
                <keyword>
                   US
                </keyword>
                <keyword>
                    Diseases
                </keyword>
            </keyWords>
            <apps>
                <appfile>Diseases.jpg</appfile>
                <applink>
                    <applink-name>Info</applink-name>
                    <value>https://www.ukrinform.ua/rubric-technology/3624230-stucnij-intelekt-navcili-peredbacati-rizik-sercevogo-napadu-j-insultu-za-rentgenom.html</value>
                </applink>
            </apps>
        </inf-meta>
        <comms>
            <comment>
                <commentText>Сподіваюсь це буде корисне відкриття!</commentText>
                <comment-author>Ілля</comment-author>
                <comment-tags>
                    <comment-tag>
                        Коментар
                    </comment-tag>
                </comment-tags>
            </comment>
        </comms>
    </article>


    <article>
        <content>
            <theme>Британія запускає програму підтримки штучного інтелекту для зменшення викидів вуглецю</theme>
            <description>
                 Уряд Великої Британії запускає інноваційну програму з підтримки використання штучного інтелекту (ШІ) для зменшення викидів вуглецю. “Запровадження цих технологій (на основі ШІ — ред.) дозволить нам заощадити витрати на електроенергію для підприємств і домогосподарств, створити висококваліфіковані робочі місця та залучити мільйони фунтів приватних інвестицій, одночасно підтримуючи цілі щодо нульових (викидів вуглецю — ред.)”, - заявив міністр науки Джодж Фріман.

На програму AI for Decarbonisation Programme уряд виділяє 1,5 мільйона фунтів стерлінгів. Вона буде запущена в два етапи. Під час першого буде доступно до 500 000 фунтів стерлінгів для фінансування віртуального Центру з інновацій ШІ та декарбонізації до березня 2025 року.
            </description>
        </content>
        <inf-meta>
            <inf>22 листопада 2022</inf>
            <author>Oksana Khrystenko</author>
            <keyWords>
                <keyword>
                 AI
                </keyword>
                <keyword>
                 UK
                </keyword>
                <keyword>
                  Environment
                </keyword>
            </keyWords>
            <apps>
                <appfile>enviroment.jpg</appfile>
                <applink>
                    <applink-name>Info</applink-name>
                    <value>https://www.ukrinform.ua/rubric-technology/3619746-britania-zapuskae-programu-pidtrimki-stucnogo-intelektu-dla-zmensenna-vikidiv-vuglecu.html</value>
                </applink>
            </apps>
        </inf-meta>
        <comms>	
            <comment>
                <commentText>Це буде дуже корисно для екології</commentText>
                <comment-author>Максим</comment-author>
                <comment-tags>
                    <comment-tag>
                      Коментар
                    </comment-tag>
                </comment-tags>			
            </comment>

            <comment>
                <commentText>Згодна з вами!</commentText>
                <comment-author>Oksana Khrystenko</comment-author>
                <comment-tags>
                    <comment-tag>
                      Автор
                    </comment-tag>
                </comment-tags>
            </comment>
        </comms>

    </article>


    <article>
        <content>
            <theme>Штучний інтелект створив картини із тваринами, які можуть зникнути через війну в Україні</theme>
            <description>
            Серію робіт в рамках міжнародної кампанії #StopEcocideUkraine представила організація UAnimals за участі Дарії Урвачової. На картинах, створених штучним інтелектом, можна побачити зубра і рись, бурого ведмедя, чорну лелеку та інших тварин, що можуть зникнути в Україні через російську агресію.
            </description>
        </content>
        <inf-meta>
            <inf>18 листопада 2022</inf>
            <author>Oksana Khrystenko</author>
            <keyWords>
                <keyword>
                 AI
                </keyword>
                <keyword>
                  Animals
                </keyword>
                <keyword>
                  Ukraine
                </keyword>
            </keyWords>
            <apps>
                <appfile>Animals.jpg</appfile>
                <applink>
                    <applink-name>Info</applink-name>
                    <value>https://www.ukrinform.ua/rubric-technology/3617358-stucnij-intelekt-stvoriv-kartini-iz-tvarinami-aki-mozut-zniknuti-cerez-vijnu-v-ukraini.html</value>
                </applink>
            </apps>
        </inf-meta>
        <comms>
            <comment>
                <commentText>Картини звісно красиві, але ситуація жахлива</commentText>
                <comment-author>Свят</comment-author>
                <comment-tags>
                    <comment-tag>
                        Коментар
                    </comment-tag>
                </comment-tags>
            </comment>
            <comment>
                <commentText>Від таких новин стає сумно</commentText>
                <comment-author>Наталі</comment-author>
                <comment-tags>
                    <comment-tag>
                        Коментар
                    </comment-tag>
                </comment-tags>
            </comment>
            <comment>
                <commentText>Дуже сумно</commentText>
                <comment-author>Oksana Khrystenko</comment-author>
                <comment-tags>
                    <comment-tag>
                        Автор
                    </comment-tag>
                </comment-tags>
            </comment>
        </comms>

    </article>

 <article>
        <content>
            <theme>Київ потрапив до однієї з номінацій нагороди Smart City Awards</theme>
            <description>
